image: debian:testing

before_script:
  - apt-get update
  - apt-get install -y ikiwiki make

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  stage: test
  script:
  - make build
  except:
  - master

pages:
  stage: deploy
  script:
  - make build
  artifacts:
    paths:
    - public
  only:
  - master
