image: debian

before_script:
  - apt-get update
  - apt-get install -y emacs make

test:
  stage: test
  script:
  - make build
  except:
  - master

pages:
  stage: deploy
  script:
  - make build
  artifacts:
    paths:
    - public
  only:
  - master
